provider "cloudflare" {
  # Same pattern as ~/1/1/home/cloudflare/rules_lists — Global API Key via bashrc:
  #   export TF_VAR_account_xyz=...
  #   export TF_VAR_email_xyz=...
  #   export TF_VAR_key_xyz=...
  api_key = var.key_xyz
  email   = var.email_xyz
}
